In [14]:
import numpy as np
from tensorflow.keras.layers import Dense
# Very simple example to add a layer
x = np.array([[200.0, 17.0]]) # input a (1,2) (1 row, 2 features) with the data: 200 degrees and 17 minutes
print(x.shape)
layer_1 = Dense(units=3, activation='sigmoid') # Layer of 'Dense' type, with 3 Neurons, who is activated by Sigmoid activation
# layer_1 in fact, turn into a function...
a1 = layer_1(x) #... so it can be called and 'activated' using the input parameter to activate, output activation, in this case, input -> layer_1(input) -> a_1
print(f'The shape of a1 is: {a1.shape}. The data is: {a1}.')
# a1 will output 3 numbers, with the shape (1,3) because layer_1 was initialized with 3 neurons, but only one row of data

# Creating the output layer/last layer
layer_2 = Dense(units = 1, activation='sigmoid') # Layer of 'Dense' type, with only a singular neuron, who is activated by Sigmoid activation
a2 = layer_2(a1) # the input will be the a1 from previous layer, a1 have a shape of (3,1), who outputs a (1, )
print(f'The shape of a1 is: {a2.shape}. The data is: {a2}.')
# This is a simplified example and is not a practical example

# Tensorflow library converts to a matrix of tensor type, to convert back to numpy array, use tensor.numpy()
print(a1)
a1np = a1.numpy()
print(a1np)

(1, 2)
The shape of a1 is: (1, 3). The data is: [[0.0000000e+00 1.0000000e+00 1.4291899e-25]].
The shape of a1 is: (1, 1). The data is: [[0.41513294]].
tf.Tensor([[0.0000000e+00 1.0000000e+00 1.4291899e-25]], shape=(1, 3), dtype=float32)
[[0.0000000e+00 1.0000000e+00 1.4291899e-25]]


## Ways to create a sequential (neural network)

### 1 - Declare layers on variables
```python
layer_1 = Dense(units=25, activation='sigmoid')
layer_2 = Dense(units=15, activation='sigmoid')
layer_3 = Dense(units=1, activation='sigmoid')
model = Sequential([layer_1, layer_2, layer_3])
```

### 2 - Instantiate layers inside Sequential
```python
layer_1 = Dense(units=25, activation='sigmoid')
layer_2 = Dense(units=15, activation='sigmoid')
layer_3 = Dense(units=1, activation='sigmoid')
model = Sequential([
    Dense(units=3, activation='sigmoid'),
    Dense(units=1, activation='sigmoid')
])
```

In [30]:
# Test using the same example but with Keras documentation
# https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dense
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, Input
from tensorflow.keras.models import Sequential

x = np.array([
    [200.0, 17.0],
    [120.0, 5.0],
    [425.0, 20.0],
    [202.0, 18.0]
]) # input
y = np.array([1, 0, 0, 1]) # target
model = Sequential()
model.add(layers.InputLayer(input_shape=(2,))) # can be omitted and will be autoset when fit() is called
model.add(Dense(units=3, activation='sigmoid', name='l1'))
model.add(Dense(units=1, activation='sigmoid', name='l2'))
print("=====DESCRIPTION OF THE NETWORK=====")
model.summary()
print("Personal Note: The parameter number is calculated by = number of features * nodes + outputs")


=====DESCRIPTION OF THE NETWORK=====
Model: "sequential_12"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
l1 (Dense)                   (None, 3)                 9         
_________________________________________________________________
l2 (Dense)                   (None, 1)                 4         
Total params: 13
Trainable params: 13
Non-trainable params: 0
_________________________________________________________________
Personal Note: The parameter number is calculated by = number of features * nodes + outputs


In [31]:
# Taken from C2_W1 lab 02 from Course2, how to see the weights
W1, b1 = model.get_layer("l1").get_weights()
W2, b2 = model.get_layer("l2").get_weights()
print(f"W1{W1.shape}:\n", W1, f"\nb1{b1.shape}:", b1)
print(f"W2{W2.shape}:\n", W2, f"\nb2{b2.shape}:", b2)

W1(2, 3):
 [[ 0.66931653  0.6387379  -0.6378816 ]
 [-0.5551859  -0.281065   -0.89989054]] 
b1(3,): [0. 0. 0.]
W2(3, 1):
 [[-0.8145307 ]
 [-0.8340565 ]
 [-0.50524336]] 
b2(1,): [0.]


In [32]:
model.compile(
    loss = tf.keras.losses.BinaryCrossentropy(),
    optimizer = tf.keras.optimizers.Adam(learning_rate=0.01),
)
model.fit(x, y, epochs=10,)

Epoch 1/10
1/1 [==============================] - 0s 372ms/step - loss: 1.0002
Epoch 2/10
1/1 [==============================] - 0s 9ms/step - loss: 0.9901
Epoch 3/10
1/1 [==============================] - 0s 17ms/step - loss: 0.9801
Epoch 4/10
1/1 [==============================] - 0s 9ms/step - loss: 0.9703
Epoch 5/10
1/1 [==============================] - 0s 10ms/step - loss: 0.9606
Epoch 6/10
1/1 [==============================] - 0s 10ms/step - loss: 0.9510
Epoch 7/10
1/1 [==============================] - 0s 7ms/step - loss: 0.9416
Epoch 8/10
1/1 [==============================] - 0s 14ms/step - loss: 0.9323
Epoch 9/10
1/1 [==============================] - 0s 11ms/step - loss: 0.9232
Epoch 10/10
1/1 [==============================] - 0s 10ms/step - loss: 0.9143


Is perceptive that loss is too high, the main problems here is low sample of dataset and no normalization has been done!

In [34]:
W1, b1 = model.get_layer("l1").get_weights()
W2, b2 = model.get_layer("l2").get_weights()
print("W1:\n", W1, "\nb1:", b1)
print("W2:\n", W2, "\nb2:", b2)

W1:
 [[ 0.66931653  0.6387379  -0.6378816 ]
 [-0.5551859  -0.281065   -0.89989054]] 
b1: [0. 0. 0.]
W2:
 [[-0.7149908 ]
 [-0.7345166 ]
 [-0.50524336]] 
b2: [0.09953984]


In [37]:
model.get_layer("l1").set_weights([W1,b1])
model.get_layer("l2").set_weights([W2,b2])
predictions = model.predict(x)
print("predictions = \n", predictions)
print(model.output_shape)

predictions = 
 [[0.20587566]
 [0.20587566]
 [0.20587566]
 [0.20587566]]
(None, 1)
